### ISSUE TITLE
Add link to join the mailing list 

### ISSUE THREAD

**Issue by bhavin192** [ritinlug/ritinlug.org#11]
A section or popup which will have text box to enter mail id, this will help users to join the Google group
something similar to this one http://pune.python.org.in/

**Comment by bhavin192** [comment]
This is the `form` which we need to include somewhere,

```html
<h3>Subscribe to <?= $group_title ?></h3>
<form action="http://groups.google.com/group/<?= $group_name ?>/boxsubscribe">
<input name="email"/>
<input type="submit" value="Subscribe" name="sub"/>
<a href="http://groups.google.com/group/<?= $group_name ?>">Browse Archives</a>
</form>
```

*source: https://stackoverflow.com/a/18789315/6202405*

**Comment by akshaygin** [comment]
Though we entered email id in form, we need to enter email id again after visiting `http://groups.google.com/group/<?= $group_name ?>/boxsubscribe` Any solution?

**Comment by bhavin192** [comment]
That answer is old, something at Google's end must have been changed now. Better would be just pass that link and let the user fill out email address. Instead of inline form we will have a button or something.
